name: 'Vite PR Coverage Insight'
description: 'Compare coverage between main and PR, post result to PR comment'
inputs:
  github-token:
    required: true
    description: 'GitHub token for PR comment'
  base:
    required: true
    description: 'Path to base coverage-summary.json'
  head:
    required: true
    description: 'Path to PR coverage-summary.json'
  test-failures:
    required: false
    description: 'Path to test failures JSON file'
  use-check-run:
    required: false
    description: 'Whether to use GitHub Check Run API'
    default: 'false'
runs:
  using: 'node16'
  main: 'dist/index.js'